import { FaArrowLeft,FaCamera,FaCode,FaGuitar,FaEnvelope,FaPhone,FaLocationDot,FaPrint,FaArrowUpRightFromSquare } from "react-icons/fa6"
import hero from "../assets/hero.png"
import "./CreativeResumePage.css"

const creativeTimeline=[
 ['2014 — 2017','Photography as a profession','Worked across wedding, fashion and creative photography; developed client handling, visual direction, retouching and storytelling skills.'],
 ['2016 — Present','Engineering career, creative mindset','Built a full-time career in electrical engineering and power-sector tendering while continuing design, photography and digital experimentation alongside it.'],
 ['Alongside work','Web, design & automation','Created business websites, portfolio experiences, Excel/VBA workflow tools and web products using WordPress, Laravel, React and Next.js.'],
 ['Now','Multidisciplinary builder','Combining engineering discipline, product thinking and visual sensibility to create useful systems and polished digital experiences.'],
]
const tools=['Photography','Photoshop','Lightroom','Graphic Design','Branding','Premiere Pro','After Effects','WordPress','React','Next.js','Laravel','Excel / VBA','Python','Visual Storytelling','Music']
const works=[['Tradesman Business OS','Business workflow, invoicing and dual-currency finance system.'],['Controlware VBA Billing System','Automation built around a real engineering-company workflow.'],['Portfolio Experiences','React-based editorial and visual web experiences.'],['Photography','Wedding, fashion, street and creative visual storytelling.']]

export default function CreativeResumePage(){return <div className="creative-cv"><nav className="creative-nav"><a href="/"><FaArrowLeft/> Portfolio</a><div><a href="/resume">Engineering Resume</a><button onClick={()=>window.print()}><FaPrint/> Print</button></div></nav><main className="creative-sheet"><header className="creative-hero"><div><p className="creative-kicker">CREATIVE TECHNOLOGIST / PHOTOGRAPHER / BUILDER</p><h1>Arafat<br/><span>Chowdhury.</span></h1><p className="creative-lead">I build useful things and visual stories—using code, design, automation and a photographer’s eye.</p><div className="creative-contact"><span><FaEnvelope/>arafat.dip.ee@gmail.com</span><span><FaPhone/>+88 01515 221433</span><span><FaLocationDot/>Dhaka, Bangladesh</span></div></div><div className="creative-photo"><img src={hero} alt="Arafat Chowdhury"/><span>CREATIVE PROFILE / 2026</span></div></header>
<section className="creative-intro"><p className="creative-label">01 / ABOUT</p><div><h2>My career is engineering.<br/>My way of thinking is broader.</h2><p>Photography was my first professional creative discipline. Later, engineering gave me structure and commercial work gave me a strong sense of real-world constraints. Coding became the bridge: a way to turn ideas and repetitive workflows into usable products.</p><p>I do not present myself as a full-time software engineer or a full-time photographer today. I am a multidisciplinary professional who understands how to observe, simplify, design and build.</p></div></section>
<section className="creative-worlds"><article><FaCamera/><span>01</span><h3>Visual</h3><p>Photography, composition, editing, branding and storytelling.</p></article><article><FaCode/><span>02</span><h3>Digital</h3><p>Web products, workflow systems, automation and practical interfaces.</p></article><article><FaGuitar/><span>03</span><h3>Creative</h3><p>Music, experimentation and the curiosity to learn beyond one discipline.</p></article></section>
<section className="creative-section"><p className="creative-label">02 / JOURNEY</p><h2>Creative journey</h2><div className="creative-timeline">{creativeTimeline.map(([year,title,text])=><article key={year+title}><time>{year}</time><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
<section className="creative-section creative-dark"><p className="creative-label">03 / SELECTED WORK</p><h2>Systems, products & stories</h2><div className="creative-work-grid">{works.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="creative-section"><div className="creative-split"><div><p className="creative-label">04 / TOOLKIT</p><h2>Tools I use to make things real.</h2></div><div className="creative-tools">{tools.map(x=><span key={x}>{x}</span>)}</div></div></section>
<section className="creative-closing"><p>ENGINEERING DISCIPLINE · DIGITAL CURIOSITY · VISUAL INSTINCT</p><h2>Different mediums.<br/>The same habit: <span>make it better.</span></h2><a href="mailto:arafat.dip.ee@gmail.com">Let’s connect <FaArrowUpRightFromSquare/></a></section>
</main></div>}
